import { ApiProperty } from '@nestjs/swagger';
import { IsEmail, IsNotEmpty, IsString, Matches } from 'class-validator';

export class VerifyPhoneCodeDto {
   @ApiProperty({
      example: 'me@example.com',
      description: 'Email address used during onboarding. The backend uses this to find the account and its generated phone OTP.',
   })
   @IsEmail()
   emailAddress!: string;

   @ApiProperty({
      example: '1234',
      minLength: 4,
      maxLength: 4,
      description: 'The 4 digit OTP generated by the backend for phone verification.',
   })
   @IsString()
   @IsNotEmpty()
   @Matches(/^\d{4}$/, { message: 'verificationCode must be a 4 digit code' })
   verificationCode!: string;
}
